name: Lint the code-base and test the code
on: [push, workflow_dispatch]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci 
      - name: lint the code
        run: npm run lint


  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci 
      - name: test the code
        run: npm run test

  
  deploying:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Running build
        run: npm run build
      - name: deploy the code
        run: echo "Deploying....."              


                   
